global:
  name: Blockchain Platform Landscape
  short_name: BPL
  mode: BPL
  repo: cncf/landscape
  website: 'https://platform.tokens-economy.com/dist/'
  short_domain: l.cncf.io
  company_url: 'https://www.tokens-economy.com'
  email: bpl@tokens-economy.com
  meta:
    title: blockchain platform landscape
    fb_admin: tokensEconomy
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@tokensEconomy'
    google_site_verification: xxxxxxxxxxxxxx
    ms_validate: xxxxxxxxxxxxxxx
  flags:
    cncf_sandbox: true
twitter:
  search: landscape.cncf.io
  url: 'https://landscape.cncf.io'
  text: Cloud Native Landscape from @CloudNativefdn
relation:
  label: CNCF Relation
  url: cncf
  values:
    - id: hosted
      label: CNCF Projects
      children:
        - id: graduated
          label: Graduated CNCF Projects
          prefix: Cloud Native
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: CNCF Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: Incubating CNCF Projects
          prefix: Cloud Native
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: CNCF Incubating
          big_picture_color: 'rgb(83, 113, 189)'
        - id: sandbox
          label: Cloud Native Sandbox Projects
          prefix: CNCF Project
          tag: Sandbox
          color: '#d1f7ff'
          big_picture_label: Cloud Native Sandbox
          big_picture_color: 'rgb(108, 165, 209)'
    - id: member
      label: CNCF Member Products/Projects
      tag: CNCF Member
    - id: false
      label: Non-CNCF Member Products/Projects
      url: 'no'
membership:
  platinum:
    name: CNCF
    label: Platinum Member
    funding: Platinum
  gold:
    name: CNCF
    label: Gold Member
    funding: Gold
  silver:
    name: CNCF
    label: Silver Member
    funding: Silver
  academic:
    name: CNCF
    label: Academic Member
    funding: Academic
  nonprofit:
    name: CNCF
    label: Nonprofit Member
    funding: Nonprofit
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
  cncf:
    name: CNCF
    label: Project
    funding: CNCF
  'false':
    funding: 'No'
home:
  header: >
    <h1>Blockchain Platform Landscape</h1> The Cloud Native Trail Map (<a target="_blank"
    href="https://raw.githubusercontent.com/cncf/trailmap/master/CNCF_TrailMap_latest.png">png</a>, <a target="_blank"
    href="https://raw.githubusercontent.com/cncf/trailmap/master/CNCF_TrailMap_latest.pdf">pdf</a>) is CNCF&apos;s recommended path through the cloud native
    landscape. The cloud native landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>) and
    serverless landscape (<a target="_blank" href="images/serverless.png">png</a>, <a target="_blank" href="images/serverless.pdf">pdf</a>) are dynamically
    generated below.
  footer: |
    Crunchbase data is used under license from Crunchbase to BPL.
ads:
  - url: 'https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/?utm_source=cncf_landscape&utm_medium=web&utm_campaign=kccnceu19'
    image: /images/info0.jpg
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Cards by age
  - url: /license=open-source
    label: Open source landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=category&headquarters=switzerland
    label: Cards from Switzerland
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: CNCF Cloud Native Landscape
    fullscreen_header: See the interactive landscape at l.cncf.io
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 1700
      height: 940
    fullscreen_size:
      width: 1720
      height: 1030
    elements:
      - type: HorizontalCategory
        category: B2B
        rows: 6
        width: 1060
        height: 230
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
      - type: LandscapeInfo
        width: 360
        height: 200
        top: 720
        left: 235
        children:
          - type: text
            text: >
              This landscape is intended as a map through the previously uncharted terrain of cloud native technologies. There are many routes to deploying a
              cloud native application, with CNCF Projects representing a particularly well-traveled path
            top: 40
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr-l.svg
            top: 40
            left: 5
            width: 90
            height: 90
          - type: title
            title: l.cncf.io
            top: 130
            left: 10
            font_size: 23
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 40
          - type: image
            image: left-logo.svg
            width: 109
            right: 5
            top: 80
          - type: image
            image: amplify.svg
            width: 55
            right: 5
            top: 115
          - type: image
            image: redpoint.svg
            width: 45
            right: 65
            top: 120
      - type: OtherLandscapeLink
        url: serverless
        title: Serverless
        layout: category
        left: 1360
        top: 535
        width: 320
        height: 180
        color: 'rgb(118, 181, 237)'
  extra:
    tab_index: 1
    url: serverless
    name: Serverless
    title: CNCF Serverless Landscape
    fullscreen_header: See the serverless interactive display at s.cncf.io
    method: getGroupedItemsForServerlessBigPicture
    size:
      width: 840
      height: 500
    fullscreen_size:
      width: 880
      height: 560
    elements:
      - type: HorizontalCategory
        category: Tools
        rows: 1
        width: 570
        height: 90
        top: 0
        left: 0
        color: 'rgb(98, 206, 230)'
      - type: HorizontalCategory
        category: Framework
        rows: 1
        width: 820
        height: 90
        top: 100
        left: 0
        fit_width: true
        color: 'rgb(57, 154, 202)'
      - type: HorizontalCategory
        category: Security
        rows: 1
        width: 240
        height: 90
        top: 0
        left: 580
        color: 'rgb(57, 152, 74)'
      - type: HorizontalCategory
        category: Platform
        rows: 2
        width: 820
        height: 120
        top: 200
        left: 0
        fit_width: true
        color: 'rgb(43, 142, 136)'
      - type: LandscapeInfo
        width: 520
        height: 120
        top: 330
        left: 5
        children:
          - type: text
            text: >
              Serverless computing refers to a new model of cloud native computing, enabled by architectures that do not require server management to build and
              run applications. This landscape illustrates a finer-grained deployment model where applications, bundled as one or more functions, are uploaded
              to a platform and then executed, scaled, and billed in response to the exact demand needed at the moment
            top: 15
            left: 90
            right: 150
            font_size: 9
          - type: image
            image: qr-s.svg
            top: 10
            left: 5
            width: 70
            height: 70
          - type: title
            title: s.cncf.io
            top: 75
            left: 10
            font_size: 16
          - type: image
            image: left-logo.svg
            width: 110
            right: 15
            top: 10
          - type: image
            image: right-logo.svg
            width: 109
            right: 15
            top: 45
          - type: image
            image: redpoint.svg
            width: 109
            right: 15
            top: 70
      - type: OtherLandscapeLink
        url: landscape
        title: Cloud Native Landscape
        layout: subcategory
        left: 580
        top: 325
        width: 305
        height: 145
        color: 'rgb(118, 181, 237)'
test:
  header: CNCF Cloud Native Interactive Landscape
  section: Graduated CNCF Projects
  logo: kubernetes.svg
update_server:
  ip: 147.75.106.211
  update_hour: 0
  update_minute: 0
